package me.wizos.loread.bean;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.NotNull;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "ARTICLE".
 */
@Entity
public class Article {

    @Id
    @NotNull
    private String id;
    private Long crawlTimeMsec;
    private Long timestampUsec;
    private String categories;
    private String title;
    private Long published;
    private Long updated;
    private Long starred;
    private String enclosure;
    private String canonical;
    private String alternate;
    private String summary;
    private String author;
    private String readState;
    private String starState;
    private String saveDir;
    private String imgState;
    private String coverSrc;
    private String originStreamId;
    private String originTitle;
    private String originHtmlUrl;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Article() {
    }

    public Article(String id) {
        this.id = id;
    }

    @Generated
    public Article(String id, Long crawlTimeMsec, Long timestampUsec, String categories, String title, Long published, Long updated, Long starred, String enclosure, String canonical, String alternate, String summary, String author, String readState, String starState, String saveDir, String imgState, String coverSrc, String originStreamId, String originTitle, String originHtmlUrl) {
        this.id = id;
        this.crawlTimeMsec = crawlTimeMsec;
        this.timestampUsec = timestampUsec;
        this.categories = categories; // note: 基本处于废弃状态，因为文章被离线后，及时订阅源的分类更新了，该字段也不会再更新。
        this.title = title;
        this.published = published;
        this.updated = updated;
        this.starred = starred;
        this.enclosure = enclosure;
        this.canonical = canonical;
        this.alternate = alternate;
        this.summary = summary;
        this.author = author;
        this.readState = readState;
        this.starState = starState;
        this.saveDir = saveDir;
        this.imgState = imgState;
        this.coverSrc = coverSrc;
        this.originStreamId = originStreamId;
        this.originTitle = originTitle;
        this.originHtmlUrl = originHtmlUrl;
    }

    @NotNull
    public String getId() {
        return id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setId(@NotNull String id) {
        this.id = id;
    }

    public Long getCrawlTimeMsec() {
        return crawlTimeMsec;
    }

    public void setCrawlTimeMsec(Long crawlTimeMsec) {
        this.crawlTimeMsec = crawlTimeMsec;
    }

    public Long getTimestampUsec() {
        return timestampUsec;
    }

    public void setTimestampUsec(Long timestampUsec) {
        this.timestampUsec = timestampUsec;
    }

    public String getCategories() {
        return categories;
    }

    public void setCategories(String categories) {
        this.categories = categories;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Long getPublished() {
        return published;
    }

    public void setPublished(Long published) {
        this.published = published;
    }

    public Long getUpdated() {
        return updated;
    }

    public void setUpdated(Long updated) {
        this.updated = updated;
    }

    public Long getStarred() {
        return starred;
    }

    public void setStarred(Long starred) {
        this.starred = starred;
    }

    public String getEnclosure() {
        return enclosure;
    }

    public void setEnclosure(String enclosure) {
        this.enclosure = enclosure;
    }

    public String getCanonical() {
        return canonical;
    }

    public void setCanonical(String canonical) {
        this.canonical = canonical;
    }

    public String getAlternate() {
        return alternate;
    }

    public void setAlternate(String alternate) {
        this.alternate = alternate;
    }

    public String getSummary() {
        return summary;
    }

    public void setSummary(String summary) {
        this.summary = summary;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public String getReadState() {
        return readState;
    }

    public void setReadState(String readState) {
        this.readState = readState;
    }

    public String getStarState() {
        return starState;
    }

    public void setStarState(String starState) {
        this.starState = starState;
    }

    public String getSaveDir() {
        return saveDir;
    }

    public void setSaveDir(String saveDir) {
        this.saveDir = saveDir;
    }

    public String getImgState() {
        return imgState;
    }

    public void setImgState(String imgState) {
        this.imgState = imgState;
    }

    public String getCoverSrc() {
        return coverSrc;
    }

    public void setCoverSrc(String coverSrc) {
        this.coverSrc = coverSrc;
    }

    public String getOriginStreamId() {
        return originStreamId;
    }

    public void setOriginStreamId(String originStreamId) {
        this.originStreamId = originStreamId;
    }

    public String getOriginTitle() {
        return originTitle;
    }

    public void setOriginTitle(String originTitle) {
        this.originTitle = originTitle;
    }

    public String getOriginHtmlUrl() {
        return originHtmlUrl;
    }

    public void setOriginHtmlUrl(String originHtmlUrl) {
        this.originHtmlUrl = originHtmlUrl;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
