package me.wizos.loread.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "IMG".
 */
public class Img {

    private Long id;
    private Integer no;
    private String name;
    private String src;
    private String articleId;
    private Integer downState;

    public Img() {
    }

    public Img(Long id) {
        this.id = id;
    }

    public Img(Long id, Integer no, String name, String src, String articleId, Integer downState) {
        this.id = id;
        this.no = no;
        this.name = name;
        this.src = src;
        this.articleId = articleId;
        this.downState = downState;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getNo() {
        return no;
    }

    public void setNo(Integer no) {
        this.no = no;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSrc() {
        return src;
    }

    public void setSrc(String src) {
        this.src = src;
    }

    public String getArticleId() {
        return articleId;
    }

    public void setArticleId(String articleId) {
        this.articleId = articleId;
    }

    public Integer getDownState() {
        return downState;
    }

    public void setDownState(Integer downState) {
        this.downState = downState;
    }

}
