package me.wizos.loread.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table "IMG".
 */
public class Img {

    private Long id;
    private Integer no;
    private String name;
    private String src;
    private String articleId;
    private Integer downState;

    // KEEP FIELDS - put your custom fields here

    /**
     * 每一个下载下来的图片，其实只关心这几个参数：
     * 1，Article_ID、NO（这2个用于在数据库中定位到图片）
     * 2，src_url（用于下载）
     * 3，src_save_path（保存路径）
     * 4，src_show_path（用于在 html 内的展示路径）
     */


    public Img() {
    }

    public Img(Long id) {
        this.id = id;
    }

    public Img(Long id, Integer no, String name, String src, String articleId, Integer downState) {
        this.id = id;
        this.no = no;
        this.name = name;
        this.src = src;
        this.articleId = articleId;
        this.downState = downState;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getNo() {
        return no;
    }

    public void setNo(Integer no) {
        this.no = no;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSrc() {
        return src;
    }

    public void setSrc(String src) {
        this.src = src;
    }

    public String getArticleId() {
        return articleId;
    }

    public void setArticleId(String articleId) {
        this.articleId = articleId;
    }

    public Integer getDownState() {
        return downState;
    }

    public void setDownState(Integer downState) {
        this.downState = downState;
    }

}
