package me.wizos.loread.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "REQUEST_LOG".
 */
public class RequestLog {

    /** Not-null value. */
    private String url;
    private String method;
    private Long logTime;
    private String headParamString;
    private String bodyParamString;

    public RequestLog() {
    }

    public RequestLog(String url) {
        this.url = url;
    }

    public RequestLog(String url, String method, Long logTime, String headParamString, String bodyParamString) {
        this.url = url;
        this.method = method;
        this.logTime = logTime;
        this.headParamString = headParamString;
        this.bodyParamString = bodyParamString;
    }

    /** Not-null value. */
    public String getUrl() {
        return url;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUrl(String url) {
        this.url = url;
    }

    public String getMethod() {
        return method;
    }

    public void setMethod(String method) {
        this.method = method;
    }

    public Long getLogTime() {
        return logTime;
    }

    public void setLogTime(Long logTime) {
        this.logTime = logTime;
    }

    public String getHeadParamString() {
        return headParamString;
    }

    public void setHeadParamString(String headParamString) {
        this.headParamString = headParamString;
    }

    public String getBodyParamString() {
        return bodyParamString;
    }

    public void setBodyParamString(String bodyParamString) {
        this.bodyParamString = bodyParamString;
    }

}
