package me.wizos.loread.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table "STATISTIC".
 */
public class Statistic {

    /**
     * Not-null value.
     */
    private String id;
    private Integer unread;
    private Integer stared;
    private Integer sum;
    private Long newestItemTimestampUsec;

    public Statistic() {
    }

    public Statistic(String id) {
        this.id = id;
    }

    public Statistic(String id, Integer unread, Integer stared, Integer sum, Long newestItemTimestampUsec) {
        this.id = id;
        this.unread = unread;
        this.stared = stared;
        this.sum = sum;
        this.newestItemTimestampUsec = newestItemTimestampUsec;
    }

    /**
     * Not-null value.
     */
    public String getId() {
        return id;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setId(String id) {
        this.id = id;
    }

    public Integer getUnread() {
        return unread;
    }

    public void setUnread(Integer unread) {
        this.unread = unread;
    }

    public Integer getStared() {
        return stared;
    }

    public void setStared(Integer stared) {
        this.stared = stared;
    }

    public Integer getSum() {
        return sum;
    }

    public void setSum(Integer sum) {
        this.sum = sum;
    }

    public Long getNewestItemTimestampUsec() {
        return newestItemTimestampUsec;
    }

    public void setNewestItemTimestampUsec(Long newestItemTimestampUsec) {
        this.newestItemTimestampUsec = newestItemTimestampUsec;
    }

}
