package me.wizos.loread.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import me.wizos.loread.bean.Feed;

import me.wizos.loread.bean.Article;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ARTICLE".
*/
public class ArticleDao extends AbstractDao<Article, String> {

    public static final String TABLENAME = "ARTICLE";

    /**
     * Properties of entity Article.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", true, "ID");
        public final static Property CrawlTimeMsec = new Property(1, Long.class, "crawlTimeMsec", false, "CRAWL_TIME_MSEC");
        public final static Property TimestampUsec = new Property(2, Long.class, "timestampUsec", false, "TIMESTAMP_USEC");
        public final static Property Categories = new Property(3, String.class, "categories", false, "CATEGORIES");
        public final static Property Title = new Property(4, String.class, "title", false, "TITLE");
        public final static Property Published = new Property(5, Long.class, "published", false, "PUBLISHED");
        public final static Property Updated = new Property(6, Long.class, "updated", false, "UPDATED");
        public final static Property Enclosure = new Property(7, String.class, "enclosure", false, "ENCLOSURE");
        public final static Property Canonical = new Property(8, String.class, "canonical", false, "CANONICAL");
        public final static Property Alternate = new Property(9, String.class, "alternate", false, "ALTERNATE");
        public final static Property Summary = new Property(10, String.class, "summary", false, "SUMMARY");
        public final static Property Author = new Property(11, String.class, "author", false, "AUTHOR");
        public final static Property ReadState = new Property(12, String.class, "readState", false, "READ_STATE");
        public final static Property StarState = new Property(13, String.class, "starState", false, "STAR_STATE");
        public final static Property ImgState = new Property(14, String.class, "imgState", false, "IMG_STATE");
        public final static Property Origin = new Property(15, String.class, "origin", false, "ORIGIN");
    };

    private DaoSession daoSession;

    private Query<Article> feed_ItemsQuery;

    public ArticleDao(DaoConfig config) {
        super(config);
    }
    
    public ArticleDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ARTICLE\" (" + //
                "\"ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: id
                "\"CRAWL_TIME_MSEC\" INTEGER," + // 1: crawlTimeMsec
                "\"TIMESTAMP_USEC\" INTEGER," + // 2: timestampUsec
                "\"CATEGORIES\" TEXT," + // 3: categories
                "\"TITLE\" TEXT," + // 4: title
                "\"PUBLISHED\" INTEGER," + // 5: published
                "\"UPDATED\" INTEGER," + // 6: updated
                "\"ENCLOSURE\" TEXT," + // 7: enclosure
                "\"CANONICAL\" TEXT," + // 8: canonical
                "\"ALTERNATE\" TEXT," + // 9: alternate
                "\"SUMMARY\" TEXT," + // 10: summary
                "\"AUTHOR\" TEXT," + // 11: author
                "\"READ_STATE\" TEXT," + // 12: readState
                "\"STAR_STATE\" TEXT," + // 13: starState
                "\"IMG_STATE\" TEXT," + // 14: imgState
                "\"ORIGIN\" TEXT);"); // 15: origin
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ARTICLE\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Article entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getId());
 
        Long crawlTimeMsec = entity.getCrawlTimeMsec();
        if (crawlTimeMsec != null) {
            stmt.bindLong(2, crawlTimeMsec);
        }
 
        Long timestampUsec = entity.getTimestampUsec();
        if (timestampUsec != null) {
            stmt.bindLong(3, timestampUsec);
        }
 
        String categories = entity.getCategories();
        if (categories != null) {
            stmt.bindString(4, categories);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(5, title);
        }
 
        Long published = entity.getPublished();
        if (published != null) {
            stmt.bindLong(6, published);
        }
 
        Long updated = entity.getUpdated();
        if (updated != null) {
            stmt.bindLong(7, updated);
        }
 
        String enclosure = entity.getEnclosure();
        if (enclosure != null) {
            stmt.bindString(8, enclosure);
        }
 
        String canonical = entity.getCanonical();
        if (canonical != null) {
            stmt.bindString(9, canonical);
        }
 
        String alternate = entity.getAlternate();
        if (alternate != null) {
            stmt.bindString(10, alternate);
        }
 
        String summary = entity.getSummary();
        if (summary != null) {
            stmt.bindString(11, summary);
        }
 
        String author = entity.getAuthor();
        if (author != null) {
            stmt.bindString(12, author);
        }
 
        String readState = entity.getReadState();
        if (readState != null) {
            stmt.bindString(13, readState);
        }
 
        String starState = entity.getStarState();
        if (starState != null) {
            stmt.bindString(14, starState);
        }
 
        String imgState = entity.getImgState();
        if (imgState != null) {
            stmt.bindString(15, imgState);
        }
 
        String origin = entity.getOrigin();
        if (origin != null) {
            stmt.bindString(16, origin);
        }
    }

    @Override
    protected void attachEntity(Article entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Article readEntity(Cursor cursor, int offset) {
        Article entity = new Article( //
            cursor.getString(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // crawlTimeMsec
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // timestampUsec
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // categories
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // title
            cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5), // published
            cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6), // updated
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // enclosure
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // canonical
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // alternate
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // summary
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // author
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // readState
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // starState
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // imgState
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15) // origin
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Article entity, int offset) {
        entity.setId(cursor.getString(offset + 0));
        entity.setCrawlTimeMsec(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setTimestampUsec(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setCategories(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setTitle(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setPublished(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
        entity.setUpdated(cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6));
        entity.setEnclosure(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setCanonical(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setAlternate(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setSummary(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setAuthor(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setReadState(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setStarState(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setImgState(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setOrigin(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(Article entity, long rowId) {
        return entity.getId();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(Article entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "items" to-many relationship of Feed. */
    public List<Article> _queryFeed_Items(String categories) {
        synchronized (this) {
            if (feed_ItemsQuery == null) {
                QueryBuilder<Article> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Categories.eq(null));
                queryBuilder.orderRaw("T.'TIMESTAMP_USEC' DESC");
                feed_ItemsQuery = queryBuilder.build();
            }
        }
        Query<Article> query = feed_ItemsQuery.forCurrentThread();
        query.setParameter(0, categories);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getFeedDao().getAllColumns());
            builder.append(" FROM ARTICLE T");
            builder.append(" LEFT JOIN FEED T0 ON T.\"CATEGORIES\"=T0.\"ID\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Article loadCurrentDeep(Cursor cursor, boolean lock) {
        Article entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Feed feed = loadCurrentOther(daoSession.getFeedDao(), cursor, offset);
        entity.setFeed(feed);

        return entity;    
    }

    public Article loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Article> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Article> list = new ArrayList<Article>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Article> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Article> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
