package me.wizos.loread.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.internal.DaoConfig;

import me.wizos.loread.db.Tag;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "TAG".
 */
public class TagDao extends AbstractDao<Tag, String> {

    public static final String TABLENAME = "TAG";

    /**
     * Properties of entity Tag.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", true, "ID");
        public final static Property Sortid = new Property(1, String.class, "sortid", false, "SORTID");
        public final static Property Title = new Property(2, String.class, "title", false, "TITLE");
        public final static Property UnreadCount = new Property(3, Integer.class, "unreadCount", false, "UNREAD_COUNT");
        public final static Property NewestItemTimestampUsec = new Property(4, Long.class, "newestItemTimestampUsec", false, "NEWEST_ITEM_TIMESTAMP_USEC");
    }

    private DaoSession daoSession;


    public TagDao(DaoConfig config) {
        super(config);
    }

    public TagDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /**
     * Creates the underlying database table.
     */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists ? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TAG\" (" + //
                "\"ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: id
                "\"SORTID\" TEXT NOT NULL ," + // 1: sortid
                "\"TITLE\" TEXT," + // 2: title
                "\"UNREAD_COUNT\" INTEGER," + // 3: unreadCount
                "\"NEWEST_ITEM_TIMESTAMP_USEC\" INTEGER);"); // 4: newestItemTimestampUsec
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_TAG_ID ON \"TAG\"" +
                " (\"ID\" ASC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TAG\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Tag entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getId());
        stmt.bindString(2, entity.getSortid());
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(3, title);
        }
 
        Integer unreadCount = entity.getUnreadCount();
        if (unreadCount != null) {
            stmt.bindLong(4, unreadCount);
        }
 
        Long newestItemTimestampUsec = entity.getNewestItemTimestampUsec();
        if (newestItemTimestampUsec != null) {
            stmt.bindLong(5, newestItemTimestampUsec);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Tag entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getId());
        stmt.bindString(2, entity.getSortid());
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(3, title);
        }
 
        Integer unreadCount = entity.getUnreadCount();
        if (unreadCount != null) {
            stmt.bindLong(4, unreadCount);
        }
 
        Long newestItemTimestampUsec = entity.getNewestItemTimestampUsec();
        if (newestItemTimestampUsec != null) {
            stmt.bindLong(5, newestItemTimestampUsec);
        }
    }

    @Override
    protected final void attachEntity(Tag entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.getString(offset + 0);
    }    

    @Override
    public Tag readEntity(Cursor cursor, int offset) {
        Tag entity = new Tag( //
                cursor.getString(offset + 0), // id
                cursor.getString(offset + 1), // sortid
                cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // title
                cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // unreadCount
                cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4) // newestItemTimestampUsec
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Tag entity, int offset) {
        entity.setId(cursor.getString(offset + 0));
        entity.setSortid(cursor.getString(offset + 1));
        entity.setTitle(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setUnreadCount(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setNewestItemTimestampUsec(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
     }
    
    @Override
    protected final String updateKeyAfterInsert(Tag entity, long rowId) {
        return entity.getId();
    }
    
    @Override
    public String getKey(Tag entity) {
        if (entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Tag entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
